# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Install all dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install
# Copy source and build
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app
# Install production dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install --omit=dev --production
# Copy built files
COPY --from=builder /app/build ./build
# Copy any necessary scripts folder for version generation (build already includes version)

CMD ["node", "build/index.js"]
